# Generated by Django 4.2.29 on 2026-04-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_report_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
