# Generated by Django 4.2.29 on 2026-04-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='op_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
